package tokens;

public enum TipoToken {
    True,
    False,
    Null,
    Identificador,
    Tipo,
    Inteiro,
    Float,
    Caractere,
    AbreChave,
    FechaChave,
    AbreColchete,
    FechaColchete,
    AbreParentese,
    FechaParentese,
    MaiorQue,
    MenorQue,
    DoisPontos,
    DoisPontosDuplos,
    PontoVirgula,
    Ponto,
    Virgula,
    Atribuicao,
    Igualdade,
    Negacao,
    Diferenca,
    Conjuncao,
    Soma,
    Subtracao,
    Multiplicacao,
    Divisao,
    Resto
}